package hk.hku.cs.swifttrip

object CityList {
    val topCities = listOf(
        CitySuggestion("New York"),
        CitySuggestion("Los Angeles"),
        CitySuggestion("London"),
        CitySuggestion("Paris"),
        CitySuggestion("Tokyo"),
        CitySuggestion("Singapore"),
        CitySuggestion("Hong Kong"),
        CitySuggestion("Dubai"),
        CitySuggestion("Bangkok"),
        CitySuggestion("Seoul"),
        CitySuggestion("Sydney"),
        CitySuggestion("Melbourne"),
        CitySuggestion("Rome"),
        CitySuggestion("Barcelona"),
        CitySuggestion("Madrid"),
        CitySuggestion("Amsterdam"),
        CitySuggestion("Berlin"),
        CitySuggestion("Frankfurt"),
        CitySuggestion("Munich"),
        CitySuggestion("Vienna"),
        CitySuggestion("Zurich"),
        CitySuggestion("Istanbul"),
        CitySuggestion("Moscow"),
        CitySuggestion("Cairo"),
        CitySuggestion("Johannesburg"),
        CitySuggestion("Mumbai"),
        CitySuggestion("Delhi"),
        CitySuggestion("Bangalore"),
        CitySuggestion("Shanghai"),
        CitySuggestion("Beijing"),
        CitySuggestion("Guangzhou"),
        CitySuggestion("Shenzhen"),
        CitySuggestion("Taipei"),
        CitySuggestion("Manila"),
        CitySuggestion("Jakarta"),
        CitySuggestion("Kuala Lumpur"),
        CitySuggestion("Ho Chi Minh City"),
        CitySuggestion("Hanoi"),
        CitySuggestion("Phuket"),
        CitySuggestion("Chiang Mai"),
        CitySuggestion("Bali"),
        CitySuggestion("Osaka"),
        CitySuggestion("Kyoto"),
        CitySuggestion("Fukuoka"),
        CitySuggestion("Auckland"),
        CitySuggestion("Wellington"),
        CitySuggestion("Chicago"),
        CitySuggestion("San Francisco"),
        CitySuggestion("Miami"),
        CitySuggestion("Las Vegas"),
        CitySuggestion("Seattle"),
        CitySuggestion("Boston"),
        CitySuggestion("Washington"),
        CitySuggestion("Atlanta"),
        CitySuggestion("Dallas"),
        CitySuggestion("Houston"),
        CitySuggestion("Toronto"),
        CitySuggestion("Vancouver"),
        CitySuggestion("Montreal"),
        CitySuggestion("Calgary"),
        CitySuggestion("Mexico City"),
        CitySuggestion("Cancun"),
        CitySuggestion("Rio de Janeiro"),
        CitySuggestion("São Paulo"),
        CitySuggestion("Buenos Aires"),
        CitySuggestion("Lima"),
        CitySuggestion("Santiago"),
        CitySuggestion("Bogota"),
        CitySuggestion("Dublin"),
        CitySuggestion("Edinburgh"),
        CitySuggestion("Manchester"),
        CitySuggestion("Brussels"),
        CitySuggestion("Copenhagen"),
        CitySuggestion("Stockholm"),
        CitySuggestion("Oslo"),
        CitySuggestion("Helsinki"),
        CitySuggestion("Warsaw"),
        CitySuggestion("Prague"),
        CitySuggestion("Budapest"),
        CitySuggestion("Athens"),
        CitySuggestion("Lisbon"),
        CitySuggestion("Porto"),
        CitySuggestion("Milan"),
        CitySuggestion("Venice"),
        CitySuggestion("Naples"),
        CitySuggestion("Dubrovnik"),
        CitySuggestion("Zagreb"),
        CitySuggestion("Belgrade"),
        CitySuggestion("Bucharest"),
        CitySuggestion("Sofia"),
        CitySuggestion("Tel Aviv"),
        CitySuggestion("Jerusalem"),
        CitySuggestion("Amman"),
        CitySuggestion("Beirut"),
        CitySuggestion("Doha"),
        CitySuggestion("Abu Dhabi"),
        CitySuggestion("Riyadh"),
        CitySuggestion("Jeddah"),
        CitySuggestion("Kuwait City"),
        CitySuggestion("Manama"),
        CitySuggestion("Muscat"),
        CitySuggestion("Colombo"),
        CitySuggestion("Dhaka"),
        CitySuggestion("Kathmandu"),
        CitySuggestion("Lahore"),
        CitySuggestion("Karachi"),
        CitySuggestion("Islamabad"),
        CitySuggestion("Tehran"),
        CitySuggestion("Baghdad"),
        CitySuggestion("Damascus"),
        CitySuggestion("Addis Ababa"),
        CitySuggestion("Nairobi"),
        CitySuggestion("Dar es Salaam"),
        CitySuggestion("Casablanca"),
        CitySuggestion("Marrakech"),
        CitySuggestion("Tunis"),
        CitySuggestion("Algiers"),
        CitySuggestion("Lagos"),
        CitySuggestion("Accra"),
        CitySuggestion("Dakar"),
        CitySuggestion("Cape Town"),
        CitySuggestion("Marrakesh"),
        CitySuggestion("Kyiv"),
        CitySuggestion("Minsk"),
        CitySuggestion("Tbilisi"),
        CitySuggestion("Yerevan"),
        CitySuggestion("Baku"),
        CitySuggestion("Almaty"),
        CitySuggestion("Tashkent"),
        CitySuggestion("Bishkek"),
        CitySuggestion("Dushanbe"),
        CitySuggestion("Ashgabat"),
        CitySuggestion("Ulaanbaatar"),
        CitySuggestion("Phnom Penh"),
        CitySuggestion("Vientiane"),
        CitySuggestion("Yangon"),
        CitySuggestion("Havana"),
        CitySuggestion("San Juan"),
        CitySuggestion("Kingston"),
        CitySuggestion("Port-au-Prince"),
        CitySuggestion("Santo Domingo"),
        CitySuggestion("Panama City"),
        CitySuggestion("San José"),
        CitySuggestion("San Salvador"),
        CitySuggestion("Tegucigalpa"),
        CitySuggestion("Managua"),
        CitySuggestion("Guatemala City"),
        CitySuggestion("Quito"),
        CitySuggestion("La Paz"),
        CitySuggestion("Asunción"),
        CitySuggestion("Montevideo"),
        CitySuggestion("Caracas"),
        CitySuggestion("Medellín"),
        CitySuggestion("Cartagena"),
        CitySuggestion("Cusco"),
        CitySuggestion("Machu Picchu"),
        CitySuggestion("Valparaíso"),
        CitySuggestion("Punta Cana"),
        CitySuggestion("Montego Bay"),
        CitySuggestion("Nassau"),
        CitySuggestion("Bridgetown"),
        CitySuggestion("Port of Spain"),
        CitySuggestion("Georgetown"),
        CitySuggestion("Paramaribo"),
        CitySuggestion("Cayenne"),
        CitySuggestion("Reykjavik"),
        CitySuggestion("Luxembourg"),
        CitySuggestion("Monaco"),
        CitySuggestion("Valletta"),
        CitySuggestion("San Marino"),
        CitySuggestion("Andorra la Vella"),
        CitySuggestion("Vaduz"),
        CitySuggestion("Skopje"),
        CitySuggestion("Podgorica"),
        CitySuggestion("Tirana"),
        CitySuggestion("Sarajevo"),
        CitySuggestion("Pristina"),
        CitySuggestion("Chisinau"),
        CitySuggestion("Vilnius"),
        CitySuggestion("Riga"),
        CitySuggestion("Tallinn"),
        CitySuggestion("Ljubljana"),
        CitySuggestion("Bratislava"),
        CitySuggestion("San Diego"),
        CitySuggestion("Denver"),
        CitySuggestion("Portland"),
        CitySuggestion("Phoenix"),
        CitySuggestion("Austin"),
        CitySuggestion("Nashville"),
        CitySuggestion("New Orleans"),
        CitySuggestion("Orlando"),
        CitySuggestion("Tampa"),
        CitySuggestion("Charlotte"),
        CitySuggestion("Detroit"),
        CitySuggestion("Minneapolis"),
        CitySuggestion("Pittsburgh"),
        CitySuggestion("Cincinnati"),
        CitySuggestion("Indianapolis"),
        CitySuggestion("Cleveland"),
        CitySuggestion("St. Louis")
    )
}