package hk.hku.cs.swifttrip.utils

data class CitySuggestion(
    val cityName: String?,
    val airportCode: String?
)

object CityList {
    val availableCities = listOf(
        CitySuggestion("New York", "JFK"),
        CitySuggestion("Los Angeles", "LAX"),
        CitySuggestion("London", "LHR"),
        CitySuggestion("Paris", "CDG"),
        CitySuggestion("Tokyo", "HND"),
        CitySuggestion("Singapore", "SIN"),
        CitySuggestion("Hong Kong", "HKG"),
        CitySuggestion("Dubai", "DXB"),
        CitySuggestion("Bangkok", "BKK"),
        CitySuggestion("Seoul", "ICN"),
        CitySuggestion("Sydney", "SYD"),
        CitySuggestion("Melbourne", "MEL"),
        CitySuggestion("Rome", "FCO"),
        CitySuggestion("Barcelona", "BCN"),
        CitySuggestion("Madrid", "MAD"),
        CitySuggestion("Amsterdam", "AMS"),
        CitySuggestion("Berlin", "BER"),
        CitySuggestion("Frankfurt", "FRA"),
        CitySuggestion("Munich", "MUC"),
        CitySuggestion("Vienna", "VIE"),
        CitySuggestion("Zurich", "ZRH"),
        CitySuggestion("Istanbul", "IST"),
        CitySuggestion("Moscow", "SVO"),
        CitySuggestion("Cairo", "CAI"),
        CitySuggestion("Johannesburg", "JNB"),
        CitySuggestion("Mumbai", "BOM"),
        CitySuggestion("Delhi", "DEL"),
        CitySuggestion("Bangalore", "BLR"),
        CitySuggestion("Shanghai", "PVG"),
        CitySuggestion("Beijing", "PEK"),
        CitySuggestion("Guangzhou", "CAN"),
        CitySuggestion("Shenzhen", "SZX"),
        CitySuggestion("Taipei", "TPE"),
        CitySuggestion("Manila", "MNL"),
        CitySuggestion("Jakarta", "CGK"),
        CitySuggestion("Kuala Lumpur", "KUL"),
        CitySuggestion("Ho Chi Minh City", "SGN"),
        CitySuggestion("Hanoi", "HAN"),
        CitySuggestion("Phuket", "HKT"),
        CitySuggestion("Chiang Mai", "CNX"),
        CitySuggestion("Bali", "DPS"),
        CitySuggestion("Osaka", "KIX"),
        CitySuggestion("Kyoto", "UKY"),
        CitySuggestion("Fukuoka", "FUK"),
        CitySuggestion("Auckland", "AKL"),
        CitySuggestion("Wellington", "WLG"),
        CitySuggestion("Chicago", "ORD"),
        CitySuggestion("San Francisco", "SFO"),
        CitySuggestion("Miami", "MIA"),
        CitySuggestion("Las Vegas", "LAS"),
        CitySuggestion("Seattle", "SEA"),
        CitySuggestion("Boston", "BOS"),
        CitySuggestion("Washington", "IAD"),
        CitySuggestion("Atlanta", "ATL"),
        CitySuggestion("Dallas", "DFW"),
        CitySuggestion("Houston", "IAH"),
        CitySuggestion("Toronto", "YYZ"),
        CitySuggestion("Vancouver", "YVR"),
        CitySuggestion("Montreal", "YUL"),
        CitySuggestion("Calgary", "YYC"),
        CitySuggestion("Mexico City", "MEX"),
        CitySuggestion("Cancun", "CUN"),
        CitySuggestion("Rio de Janeiro", "GIG"),
        CitySuggestion("São Paulo", "GRU"),
        CitySuggestion("Buenos Aires", "EZE"),
        CitySuggestion("Lima", "LIM"),
        CitySuggestion("Santiago", "SCL"),
        CitySuggestion("Bogota", "BOG"),
        CitySuggestion("Dublin", "DUB"),
        CitySuggestion("Edinburgh", "EDI"),
        CitySuggestion("Manchester", "MAN"),
        CitySuggestion("Brussels", "BRU"),
        CitySuggestion("Copenhagen", "CPH"),
        CitySuggestion("Stockholm", "ARN"),
        CitySuggestion("Oslo", "OSL"),
        CitySuggestion("Helsinki", "HEL"),
        CitySuggestion("Warsaw", "WAW"),
        CitySuggestion("Prague", "PRG"),
        CitySuggestion("Budapest", "BUD"),
        CitySuggestion("Athens", "ATH"),
        CitySuggestion("Lisbon", "LIS"),
        CitySuggestion("Porto", "OPO"),
        CitySuggestion("Milan", "MXP"),
        CitySuggestion("Venice", "VCE"),
        CitySuggestion("Naples", "NAP"),
        CitySuggestion("Dubrovnik", "DBV"),
        CitySuggestion("Zagreb", "ZAG"),
        CitySuggestion("Belgrade", "BEG"),
        CitySuggestion("Bucharest", "OTP"),
        CitySuggestion("Sofia", "SOF"),
        CitySuggestion("Tel Aviv", "TLV"),
        CitySuggestion("Jerusalem", "JRS"),
        CitySuggestion("Amman", "AMM"),
        CitySuggestion("Beirut", "BEY"),
        CitySuggestion("Doha", "DOH"),
        CitySuggestion("Abu Dhabi", "AUH"),
        CitySuggestion("Riyadh", "RUH"),
        CitySuggestion("Jeddah", "JED"),
        CitySuggestion("Kuwait City", "KWI"),
        CitySuggestion("Manama", "BAH"),
        CitySuggestion("Muscat", "MCT"),
        CitySuggestion("Colombo", "CMB"),
        CitySuggestion("Dhaka", "DAC"),
        CitySuggestion("Kathmandu", "KTM"),
        CitySuggestion("Lahore", "LHE"),
        CitySuggestion("Karachi", "KHI"),
        CitySuggestion("Islamabad", "ISB"),
        CitySuggestion("Tehran", "IKA"),
        CitySuggestion("Baghdad", "BGW"),
        CitySuggestion("Damascus", "DAM"),
        CitySuggestion("Addis Ababa", "ADD"),
        CitySuggestion("Nairobi", "NBO"),
        CitySuggestion("Dar es Salaam", "DAR"),
        CitySuggestion("Casablanca", "CMN"),
        CitySuggestion("Marrakech", "RAK"),
        CitySuggestion("Tunis", "TUN"),
        CitySuggestion("Algiers", "ALG"),
        CitySuggestion("Lagos", "LOS"),
        CitySuggestion("Accra", "ACC"),
        CitySuggestion("Dakar", "DSS"),
        CitySuggestion("Cape Town", "CPT"),
        CitySuggestion("Marrakesh", "RAK"),
        CitySuggestion("Kyiv", "KBP"),
        CitySuggestion("Minsk", "MSQ"),
        CitySuggestion("Tbilisi", "TBS"),
        CitySuggestion("Yerevan", "EVN"),
        CitySuggestion("Baku", "GYD"),
        CitySuggestion("Almaty", "ALA"),
        CitySuggestion("Tashkent", "TAS"),
        CitySuggestion("Bishkek", "FRU"),
        CitySuggestion("Dushanbe", "DYU"),
        CitySuggestion("Ashgabat", "ASB"),
        CitySuggestion("Ulaanbaatar", "ULN"),
        CitySuggestion("Phnom Penh", "PNH"),
        CitySuggestion("Vientiane", "VTE"),
        CitySuggestion("Yangon", "RGN"),
        CitySuggestion("Havana", "HAV"),
        CitySuggestion("San Juan", "SJU"),
        CitySuggestion("Kingston", "KIN"),
        CitySuggestion("Port-au-Prince", "PAP"),
        CitySuggestion("Santo Domingo", "SDQ"),
        CitySuggestion("Panama City", "PTY"),
        CitySuggestion("San José", "SJO"),
        CitySuggestion("San Salvador", "SAL"),
        CitySuggestion("Tegucigalpa", "TGU"),
        CitySuggestion("Managua", "MGA"),
        CitySuggestion("Guatemala City", "GUA"),
        CitySuggestion("Quito", "UIO"),
        CitySuggestion("La Paz", "LPB"),
        CitySuggestion("Asunción", "ASU"),
        CitySuggestion("Montevideo", "MVD"),
        CitySuggestion("Caracas", "CCS"),
        CitySuggestion("Medellín", "MDE"),
        CitySuggestion("Cartagena", "CTG"),
        CitySuggestion("Cusco", "CUZ"),
        CitySuggestion("Machu Picchu", "CUZ"),
        CitySuggestion("Valparaíso", "SCL"),
        CitySuggestion("Punta Cana", "PUJ"),
        CitySuggestion("Montego Bay", "MBJ"),
        CitySuggestion("Nassau", "NAS"),
        CitySuggestion("Bridgetown", "BGI"),
        CitySuggestion("Port of Spain", "POS"),
        CitySuggestion("Georgetown", "GEO"),
        CitySuggestion("Paramaribo", "PBM"),
        CitySuggestion("Cayenne", "CAY"),
        CitySuggestion("Reykjavik", "KEF"),
        CitySuggestion("Luxembourg", "LUX"),
        CitySuggestion("Monaco", "NCE"),
        CitySuggestion("Valletta", "MLA"),
        CitySuggestion("San Marino", "RMI"),
        CitySuggestion("Andorra la Vella", "LEU"),
        CitySuggestion("Vaduz", "ZRH"),
        CitySuggestion("Skopje", "SKP"),
        CitySuggestion("Podgorica", "TGD"),
        CitySuggestion("Tirana", "TIA"),
        CitySuggestion("Sarajevo", "SJJ"),
        CitySuggestion("Pristina", "PRN"),
        CitySuggestion("Chisinau", "KIV"),
        CitySuggestion("Vilnius", "VNO"),
        CitySuggestion("Riga", "RIX"),
        CitySuggestion("Tallinn", "TLL"),
        CitySuggestion("Ljubljana", "LJU"),
        CitySuggestion("Bratislava", "BTS"),
        CitySuggestion("San Diego", "SAN"),
        CitySuggestion("Denver", "DEN"),
        CitySuggestion("Portland", "PDX"),
        CitySuggestion("Phoenix", "PHX"),
        CitySuggestion("Austin", "AUS"),
        CitySuggestion("Nashville", "BNA"),
        CitySuggestion("New Orleans", "MSY"),
        CitySuggestion("Orlando", "MCO"),
        CitySuggestion("Tampa", "TPA"),
        CitySuggestion("Charlotte", "CLT"),
        CitySuggestion("Detroit", "DTW"),
        CitySuggestion("Minneapolis", "MSP"),
        CitySuggestion("Pittsburgh", "PIT"),
        CitySuggestion("Cincinnati", "CVG"),
        CitySuggestion("Indianapolis", "IND"),
        CitySuggestion("Cleveland", "CLE"),
        CitySuggestion("St. Louis", "STL")
    )
}
